_extends: .github

repository:
    description: ⚽ A microservice that processes data from external feed providers.
    homepage: https://github.com/KarolosLykos/sportnews
    topics: go, golang, grpc, mongodb, redis
    private: false
    
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: []
      required_linear_history: true
