version: "2.6"

services:
    sportsnews:
        container_name: sportsnews_api
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            MONGO_HOST: mongodb
            REDIS_HOST: redis
        ports:
            - "8081:8081"
        restart: always
        depends_on:
            - mongodb
            - redis

    mongodb:
        image: mongo:latest
        container_name: sportsnews_mongodb
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=sportsnews
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=secret
        ports:
            - 27017:27017

    redis:
        image: redis
        container_name: sportsnews_redis
        restart: always
        ports:
            - "6379:6379"

    redis-commander:
        image: rediscommander/redis-commander:latest
        container_name: sportsnews_redis-commander
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "1235:8081"